### ISSUE TITLE
Problems linking with (external) Spectrum MPI

### ISSUE THREAD

**Issue by adammoody** [open-ce/LightGBM-feedstock#9]
I would like to build Open-CE to use the system installed MPI library, which is IBM Spectrum MPI.  I am building Open-CE in a Singularity image based on the Docker image here:

https://github.com/open-ce/open-ce/blob/master/images/builder-cuda-ppc64le/Dockerfile.cuda-10.2

I am running the build on a system with Spectrum MPI installed to a path that is exposed to the image with a ``-B`` binding.  I am running the following command:
```
./open-ce/open-ce/open-ce build env --output_folder /path/to/condabuild --mpi_types system --build_types cuda --cuda_versions 10.2 ./open-ce-environments/envs/lightgbm-env.yaml
```
When building LightGBM, cmake fails to find MPI:
```
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at /dev/shm/anaconda/conda-bld/lightgbm-base_1613696077157/_build_env/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)

      Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.  
```
Looking at the CMakeError.txt output, I can see that it fails to find some dependent libraries like ``libopen-pal`` and ``libopen-rte`` while trying a test link:
```
/dev/shm/anaconda/conda-bld/lightgbm-base_1613696077157/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: warning: libopen-rte.so.3, needed by /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/lib/libmpi_ibm.so, not found (try using -rpath or -rpath-link)
/dev/shm/anaconda/conda-bld/lightgbm-base_1613696077157/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: warning: libopen-pal.so.3, needed by /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/lib/libmpi_ibm.so, not found (try using -rpath or -rpath-link)
/dev/shm/anaconda/conda-bld/lightgbm-base_1613696077157/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: warning: libz.so.1, needed by /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/lib/libmpi_ibm.so, not found (try using -rpath or -rpath-link)
/dev/shm/anaconda/conda-bld/lightgbm-base_1613696077157/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: warning: libhwloc_ompi.so.15, needed by /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/lib/libmpi_ibm.so, not found (try using -rpath or -rpath-link)
```
I have nearly hacked around the problem by listing a set of libraries in ``LDFLAGS``, however that leads to another problem.

Is there a recommended way to build with Spectrum MPI?

I could perhaps add it to the container image, but I'm wondering if there are other recommended steps.  Thanks.

**Comment by npanpaliya** [comment]
I'm looking into this.

**Comment by npanpaliya** [comment]
@adammoody - What is the path in the image where spectrum MPI libs are present?

I tried installing spectrum-mpi using `conda install spectrum-mpi -c https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda` in the container itself and did the LightGBM build using the command you mentioned, and it went just fine.

**Comment by adammoody** [comment]
Thanks for looking into this, @npanpaliya .  I don't currently have Spectrum MPI installed in the image.  Instead it is installed on the host system on which the image is running, and that external MPI is exposed by starting the image with a ``-B`` option listing that host install path.  I want to be sure that the Open-CE build is compatible with the MPI library that is installed on the host and figured that was safer than installing a different MPI in the image itself which could be a different version or even the same version but configured in a different way that makes it incompatible.

Having said that, I'll try the ``conda install spectrum-mpi`` step you mention here as a potential work around / fix.  I'll get back to you on that.  In case we end up needing to build against this external Spectrum MPI, I'll also provide more detail on my setup.

We have multiple versions of Spectrum MPI installed on the host system, and each is installed to its own directory path.  At any given time, one of those is identified as the default, though users can select other versions if needed.  For now, I'm just trying to build Open-CE against our default MPI.  This happens to be installed to a path like: ``/path/to/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.11.12``.  In starting the Singularity image, this external directory tree on the host is bound into the image with ``singularity shell -B /path/to/spectrum-mpi open-ce-builder.sif``.

Before running the opence command, I also add the bin and lib directories for MPI to ``PATH`` and ``LD_LIBRARY_PATH`` so that ``mpicc`` is in the path and to help any configure step that might rely on the lib path:
```
# add path to pick up system install of Spectrum MPI
export PATH="/path/to/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.11.12/bin:$PATH"
export LD_LIBRARY_PATH="/path/to/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.11.12/lib:$LD_LIBRARY_PATH"

./open-ce/open-ce/open-ce build env --output_folder /path/to/condabuild --mpi_types system --build_types cuda --cuda_versions 10.2 ./open-ce-environments/envs/lightgbm-env.yaml
```

It's under this configuration that CMake throws the above error when testing for MPI.  It tries to link a test program, and that link fails because it can't find a number of libraries that ``libmpi_ibm.so`` depends on.  I have found that I can help CMake find those libraries by listing all of those libraries in ``LDFLAGS`` like so:
```
export LDFLAGS="-L/path/to/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.11.12/lib -lopen-pal -lopen-rte -levent_pthreads -lhwloc_ompi -levent -L/usr/lib64 -lz"
```

That almost works, but then some of those settings lead to other problems.

In case we end up needing to build against this external Spectrum MPI, are you able to reproduce this?

**Comment by adammoody** [comment]
I can verify that ``conda install spectrum-mpi`` leads to a successful build:
```
conda install spectrum-mpi -c https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda
```
In particular, those CMake tests for LightGBM now pass:
```
-- Found MPI_C: /dev/shm/anaconda/lib/libmpiprofilesupport.so (found version "3.1") 
-- Found MPI_CXX: /dev/shm/anaconda/lib/libmpiprofilesupport.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI libraries: /dev/shm/anaconda/lib/libmpiprofilesupport.so/dev/shm/anaconda/lib/libmpi_ibm.so
-- MPI C++ libraries: /dev/shm/anaconda/lib/libmpiprofilesupport.so/dev/shm/anaconda/lib/libmpi_ibm.so
```
Hopefully those packages will work.  Thanks, @npanpaliya .

That also sheds a clue on why CMake is failing to link with my external MPI library.  I can see that the Spectrum MPI that is installed by conda has an embedded RPATH setting of ``$ORIGIN/.`` and so it finds its dependent libs in the same directory where it is installed:
```
Singularity> readelf -d /dev/shm/anaconda/lib/libmpi_ibm.so | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/.]

Singularity> ldd /dev/shm/anaconda/lib/libmpi_ibm.so
        linux-vdso64.so.1 =>  (0x00007ffff7f90000)
        libopen-rte.so.3 => /dev/shm/anaconda/lib/./libopen-rte.so.3 (0x00007ffff7d10000)
        libopen-pal.so.3 => /dev/shm/anaconda/lib/./libopen-pal.so.3 (0x00007ffff7c20000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ffff7be0000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007ffff7bb0000)
        libhwloc_ompi.so.15 => /dev/shm/anaconda/lib/./libhwloc_ompi.so.15 (0x00007ffff7b30000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff7a40000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff7a10000)
        libevent-2.1.so.6 => /dev/shm/anaconda/lib/./libevent-2.1.so.6 (0x00007ffff7980000)
        libevent_pthreads-2.1.so.6 => /dev/shm/anaconda/lib/./libevent_pthreads-2.1.so.6 (0x00007ffff7940000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff7900000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff7710000)
        /lib64/ld64.so.2 (0x00007ffff7fb0000)
```
There is an RPATH entry in my external Spectrum MPI library, but it looks like it still points to a temporary build path and not the install location:
```
Singularity> readelf -d /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib/libmpi_ibm.so | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/__SMPI_build_dir_______________________________________/exports/optimized/lib:/__SMPI_build_dir________________________/hwloc/hwloc-2.0.3p0_ompi-cuda-10.1-libevent-2.1.8/hwloc_install/lib:/__SMPI_build_dir________________________/libevent/libevent-2.1.8/lib]

Singularity> ldd /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib/libmpi_ibm.so
        linux-vdso64.so.1 =>  (0x00007ffff7f90000)
        libopen-rte.so.3 => not found
        libopen-pal.so.3 => not found
        librt.so.1 => /lib64/librt.so.1 (0x00007ffff7dd0000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007ffff7da0000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ffff7d60000)
        libhwloc_ompi.so.15 => not found
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff7c70000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff7c40000)
        libevent-2.1.so.6 => not found
        libevent_pthreads-2.1.so.6 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff7c00000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff7a10000)
        /lib64/ld64.so.2 (0x00007ffff7fb0000)
```
I'm guessing that maybe if I fix the RPATH in my external installed Spectrum MPI lib that might fix things.  I suppose that could be done the forceful way with chrpath or readelf, but maybe there is a better way?

Do you know if anything was done to address that in the spectrum-mpi installed by conda?

**Comment by npanpaliya** [comment]
Thank you @adammoody for summarizing your setup. I'll try recreate the problem and see how it can be fixed.

I'm also checking spectrum-mpi conda recipe and don't see any special setting for RPATHs. I'll explore more on this and revert.

**Comment by adammoody** [comment]
I found that I can get LightGBM to build with my system install of Spectrum MPI, but I had to do two things.

First, I set the RPATH in my Spectrum MPI libraries with something like:
```
chrpath -r '$ORIGIN' libmpi_ibm.so
chrpath -r '$ORIGIN' libmpiprofile.so
```
For good measure, I also did this with ``libopen-rte.so`` and ``libopen-pal.so``, though I'm not sure those are really necessary.

That resolved the missing MPI libs.  However, I still hit a problem in the LightGBM CMake configure step due to undefinded symbols from ``libz``, like ``deflate``.
```
/dev/shm/anaconda/conda-bld/lightgbm-base_1614122849133/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: warning: libz.so.1, needed by /usr/global/tools/opence/blueos_3_ppc64le_ib_p9/singularity/tempsmpi/spectrum-mpi/lib/libmpi_ibm.so, not found (try using -rpath or -rpath-link)
/dev/shm/anaconda/conda-bld/lightgbm-base_1614122849133/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: /usr/global/tools/opence/blueos_3_ppc64le_ib_p9/singularity/tempsmpi/spectrum-mpi/lib/libopen-rte.so.3: undefined reference to `inflateEnd'
/dev/shm/anaconda/conda-bld/lightgbm-base_1614122849133/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: /usr/global/tools/opence/blueos_3_ppc64le_ib_p9/singularity/tempsmpi/spectrum-mpi/lib/libopen-rte.so.3: undefined reference to `deflate'
```

To get past that, I also set ``LDFLAGS`` to point to the libz in my ``anaconda/lib`` like so:
```
export LDFLAGS="-L/dev/shm/anaconda/lib -lz"
```
The link step in the CMake test uses ``ld`` from this package:
```
/dev/shm/anaconda/conda-bld/lightgbm-base_1614122849133/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld
```
Apparently that ``ld`` doesn't know to link to libs in either ``/usr/lib64`` or the conda lib directory, both of which have contain a ``libz.so``.

I think this second step is not needed when using the conda-installed Spectrum MPI, because ``libmpi_ibm.so`` is installed into the conda lib directory ``anaconda/lib``, so that then the RPATH entry of ``$ORIGIN/.`` in ``libmpi_ibm.so`` happens to point the same directory that also contains a ``libz.so``.

I suspect this might be reproduced so long as Spectrum MPI is installed to some directory other than ``/usr/lib64`` and the anaconda lib directory, which is ``/dev/shm/anaconda/lib`` in my case.

**Comment by adammoody** [comment]
This does seem to track back to using ``powerpc64le-conda_cos7-linux-gnu/bin/ld`` when trying to link to libraries outside of the conda/lib directory, like an external install of Spectrum MPI.  I can reproduce this problem excluding Open-CE with just a CMake build of a simple MPI project using the conda-installed gcc/ld tools.

A simple MPI program:
```
// testmpi.c
#include <stdlib.h>
#include "mpi.h"
int main (int argc, char* argv[])
{
  MPI_Init(&argc, &argv);
  MPI_Finalize();
  return 0;
}
```
A CMakeLists.txt file to build the program:
```
# CMakeLists.txt
PROJECT(TESTMPI)
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
FIND_PACKAGE(MPI REQUIRED)
ADD_EXECUTABLE(testmpi testmpi.c)
INSTALL(PROGRAMS testmpi DESTINATION bin)
```
Commands to install anaconda, cmake, and gcc/ld, then attempt to build under that environment.
```
bash ./Miniconda3-latest-Linux-ppc64le.sh -b -f -p anaconda
source anaconda/bin/activate
conda install -y cmake gxx_linux-ppc64le=7.3

mkdir build
cd build
cmake ../
```
This fails with the same errors reported above.

Setting LDFLAGS to point to those external libs just before the cmake command resolves the problem:
```
export LDFLAGS="-L/path/to/spectrum-mpi/lib -lopen-rte -lopen-pal -lhwloc_ompi -levent -levent_pthreads -L/usr/lib64 -lz"
```

**Comment by adammoody** [comment]
I'm still not sure of the best fix yet, but these pages also shed some light on things.

This page describes the conda compiler tools and their motivation:
https://www.anaconda.com/blog/utilizing-the-new-compilers-in-anaconda-distribution-5

It sounds the goal is to set the tools up to make it hard to build against software outside of conda by design, in order to be sure that the resulting package only has internal dependencies.

In fact, the ``ld`` being used apparently takes measures to avoid linking to system software.  The ``link_libgcc`` entry in gcc specs file has been modified to add an rpath to the anaconda lib directory where internal dependencies are expected to be installed:
https://conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#

The specs file being used here seems to be at ``anaconda/lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/specs``

One could perhaps modify that same gcc specs file to list -L flags to other directories, like the path to the external install of Spectrum and libz, though that seems like a big hammer:
https://stackoverflow.com/questions/7493620/inhibit-default-library-paths-with-gcc

Another idea I've seen suggested is to place symlinks to the external libs in the ``anaconda/lib`` directory, which would make it seem as though the software is installed in anaconda.  I haven't tried that yet.

I'm still searching for clean ways to request that version of ``ld`` to link to external libs with less hacking.

**Comment by bethune-bryant** [comment]
The system compiler workaround should resolve this issue, but we opened a new issue to specifically address this shortcoming:
https://github.com/open-ce/open-ce-builder/issues/104
